# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: syed2000
service: aws-node-express-api

custom:
  env:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DATABASE_URL

provider:
  name: aws
  runtime: nodejs24.x # 👈 Update this from nodejs20.x to nodejs24.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  environment:
    DATABASE_URL: ${env:DATABASE_URL, "fallback-value-if-not-set"}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
