# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: syed2000
# Lambda function name must be unique across all AWS accounts in the same region. The default is to use the service name, but you can override it here.
service: serverless-nodejs-api-yt

custom:
  env:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DATABASE_URL

provider:
  name: aws
  runtime: nodejs24.x # 👈 Update this from nodejs20.x to nodejs24.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  iam:
    role:
      # In the policy.json file, we set up like /serverless-*/ to allow access to all functions in this service. 
      # If you want to restrict it to a specific function, you can change the wildcard to the function name. 
      name: serverless-my-ssm-role
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - "ssm:GetParameter"
            - "ssm:GetParameters"
            - "ssm:GetParametersByPath"
            - "ssm:DescribeParameters"
            - "ssm:GetParameterHistory"

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
